name: builds

on: [push, pull_request]

jobs:
  build-windows-2022:
    runs-on: windows-2022
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: build (vs 2022)
        shell: cmd
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64
          call build raddbg msvc debug
          call build raddbg_from_pdb msvc debug
          call build raddbg_from_dwarf msvc debug
          call build raddbg clang debug
          call build raddbg_from_pdb clang debug
          call build raddbg_from_dwarf clang debug
